### ISSUE TITLE
Failed to install your role

### ISSUE THREAD

**Issue by qs5779** [ahuffman/ansible-hosts#2]
$ ansible-galaxy install ahuffman.hosts
Starting galaxy role install process
- downloading role 'hosts', owned by ahuffman
[WARNING]: - ahuffman.hosts was NOT installed successfully: Unable to compare role versions (v1.1, 2.0.0, 2.0.1) to
determine the most recent version due to incompatible version formats. Please contact the role author to resolve
versioning conflicts, or specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

My version into:

$ ansible-galaxy --version
ansible-galaxy [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/jim/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible-galaxy
  python version = 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True

**Comment by ahuffman** [comment]
Thanks for the report @qs5779 turns out I had some old releases in a vX.X.X format that is no longer compatible (for a very long time) with galaxy.  I removed the releases and tags from GitHub and reimported to Galaxy.  I verified I was able to reproduce your install issue, and after what I just described it successfully installs.
